# Dev overrides
spring.datasource.url=jdbc:sqlite:./dev-alumnibeacon.db
spring.jpa.show-sql=true
logging.level.com.alumnibeacon=DEBUG
august.adapter.url=http://localhost:8000

# JWT cookie does not require HTTPS in dev (HTTP localhost)
cookie.secure=false
